# Generated by Django 5.2.6 on 2025-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shorts', 'Shorts'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('equipment', 'Training Equipment'), ('accessories', 'Accessories'), ('merchandise', 'Merchandise')], default='update', max_length=20),
        ),
    ]
