# Generated by Django 5.2.6 on 2025-09-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shorts', 'Shorts'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('equipment', 'Training Equipment'), ('accessories', 'Accessories'), ('merchandise', 'Merchandise')], default='merchandise', max_length=20),
        ),
    ]
